### ISSUE TITLE
Can this be seen by you Saif?

### ISSUE THREAD

**Issue by SparrowMike** [SparrowMike/Extension#3]

**Comment by SparrowMike** [comment]
This Project suppose to be private so I think only me and you can see it? Need to check this hahaha

**Comment by SparrowMike** [comment]
The cool thing is that we can easily track this on our phones and add as we go.

Can we please prioritise using GitHub for as many features as possible

**Comment by MohdSaifulM** [comment]
yeah this can be seen by me. And i will prioritize using github
